source "http://rubygems.org"

gem "capistrano"
gem "capistrano-ext"
gem "sinatra"
gem "dm-core"
gem "dm-types"
gem "dm-mysql-adapter"
gem "rspec"
gem "nokogiri"
gem "json"
gem "shotgun", :group => "development"
gem "thin", :group => "development"