source "http://rubygems.org"

gem "capistrano"
gem "capistrano-ext"
gem "sinatra"
gem "rack-test"
gem "rspec"
gem "nokogiri"
gem "json"
gem "shotgun", :group => "development"
gem "thin", :group => "development"